### ISSUE TITLE
Add Fuel Level Sensor

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#241]
This is a template issue from the project to get more SkodaConnect sensors into `homeassistant-myskoda`.

**Sensor**
Fuel Level

**Last known status**
Discovered in MySkoda API's

**Comment by prvakt** [comment]
PR #265

**Comment by msandvold** [comment]
I set up a sensor that "calculates liter:
  
```
   - platform: template
     sensors:
       skoda_drivstoff_liter:
           friendly_name: Fuel level L
           unit_of_measurement: "L"
           value_template: "{{ (sensor.xxxxx) | float * 0.xx) | round(3) }}"
           unique_id: sensor.skoda_fuel_liter
```
Just your sensor id and fueltank capasity -> xx
