### ISSUE TITLE
Device Tracker - Automation

### ISSUE THREAD

**Issue by AJTaylor79** [skodaconnect/homeassistant-myskoda#263]
Device Tracker - Skoda Enyaq

Can someone please tell me how I can use use the device tracker on the Enyaq to provide an automation when the car leaves or enters a location.

The "Position" picks up the Zones and either reflects Home, Zone, Unknown, Vehicle in Motion or Away

Whatever I try the automation just does not seem to work.

Any ideas on what I can do to make it work?

Many Thanks

Andrew

**Comment by WebSpider** [comment]
You need to compare against the state of the `device_tracker` entity, as can be seen in 'Developers Tools' in HA (bottom left menu), not against the displayed state in frontend, as this is subject to translations.

**Comment by AJTaylor79** [comment]
So if I create the Automation using an Entity and then State, how would I go about filling in the Attribute, From and To? I doesn't seem to allow me to use the zone location in this case? Thanks for your help

**Comment by WebSpider** [comment]
:shrug:

**Comment by AJTaylor79** [comment]
@MilanDasek I managed to get mine working using the following automation. The trigger is a state change from the Entry: Škoda Enyaq Position and From vehicle_in_motion To Home, hope this helps?

```
alias: Skoda - Has arrived home
description: ""
triggers:
  - trigger: state
    entity_id:
      - device_tracker.skoda_enyaq_position
    from: vehicle_in_motion
    to: home
conditions: []
actions:
  - action: notify.pushover
    metadata: {}
    data:
      message: The Skoda has arrived home
mode: single
```
