### ISSUE TITLE
Remove "in KM" from "Next inspection" and "Oil service" sensors

### ISSUE THREAD

**Issue by cholek3** [skodaconnect/homeassistant-myskoda#496]
Hi,

First of all, thank you for your work on this add-on.

Do API requests also provide imperial measurements for sensors? I have my Kamiq set for UK market, so all measurements are in miles, but add-on provides ```sensor.skoda_kamiq_range```, ```sensor.skoda_kamiq_next_inspection_in_km```, ```sensor.skoda_kamiq_oil_service_in_km``` and ```sensor.skoda_kamiq_mileage``` are in kilometres. If so, could we have those sensors providing measurements in miles, please?

I am having difficulties converting kilometres into miles, as I am getting different factors:
My current measurements from addon and what it shows in car:
~~range: 249m (car) / 402km (addon) = 1.614457831325301~~
~~mileage: 117m (car)/117.2m (trip mileage) /188km (addon) = 1.606837606837607/1.604095563139932~~
127.6m / 205.4km = 1.609717868338558

**Comment by cholek3** [comment]
Well, I guess I will answer myself to this feature request. Just downloaded diagnostics file, and I see API only reports those values in kilometres, so I had to create template sensor:
```
- platform: template
  sensors:
    skoda_kamiq_range_in_miles:
      friendly_name: "Skoda Kamiq Range in miles"
      unit_of_measurement: 'm'
      device_class: distance
      icon_template: mdi:gas-station
      value_template: "{{ ((states('sensor.skoda_kamiq_range') | float(0) / 1.609717868338558 | float(0) )) | round(0) }}"

    skoda_kamiq_next_inspection_in_miles:
      friendly_name: "Skoda Kamiq service in miles"
      unit_of_measurement: 'm'
      device_class: distance
      icon_template: mdi:car-wrench
      value_template: "{{ ((states('sensor.skoda_kamiq_next_inspection_in_km') | float(0) / 1.609717868338558 | float(0) )) | round(0) }}"

    skoda_kamiq_mileage_in_miles:
      friendly_name: "Skoda Kamiq mileage in miles"
      unit_of_measurement: 'm'
      device_class: distance
      icon_template: mdi:counter
      value_template: "{{ ((states('sensor.skoda_kamiq_mileage') | float(0) / 1.609717868338558 | float(0) )) | round(0) }}"

    skoda_kamiq_oil_service_in_miles:
      friendly_name: "Skoda Kamiq oil service in miles"
      unit_of_measurement: 'm'
      device_class: distance
      icon_template: mdi:oil
      value_template: "{{ ((states('sensor.skoda_kamiq_oil_service_in_km') | float(0) / 1.609717868338558 | float(0) )) | round(0) }}"
```

Can somebody correct me if I am wrong.
