### ISSUE TITLE
Trying to create a "force refresh" button [enyaq]

### ISSUE THREAD

**Issue by newbuilder22** [skodaconnect/homeassistant-myskoda#558]
Hi
Having read the readme it mentions that polling can be turned off and 
`device_tracker.skoda_4ever` could be used. 

I don't want to switch polling off but want to force a refresh after I send a command.

e.g. Ask the charger to start charging and send a manual polling command 
`action: homeassistant.update_entity
target:
  entity_id: device_tracker.skoda_4ever`

to update the dashboard with a current feed. 

I note that when I look through the entities in the integration that 

`device_tracker.skoda_4ever`

is not there - should it be or is it hidden?

**Comment by prvakt** [comment]
its just an example because name of the entity differs per vehicle.. There is only one device_tracker from our integration so just use that one.

The full name key is `device_tracker.skoda_xxx_yyy` where `xxx` is model of your car and `yyy` is `position` translated to your locale
In my case its - `device_tracker.skoda_superb_combi_position`.. If I remember correctly you have Enyaq so I guess your sensor will be called `device_tracker.skoda_enyaq_position` but if you are using different language last part of the name may differ

**Comment by msandvold** [comment]
Hi.

I used a button for this in UI, to uppdate the inteties you choose.

```
show_name: false
show_icon: true
type: button
tap_action:
  action: perform-action
  perform_action: homeassistant.update_entity
  target: {}
  data:
    entity_id:
      - climate.xxxx
      - device_tracker.xxxx
      - sensor.xxx
show_state: true
icon_height: 30px
entity: sensor.skoda_superb_combi_last_updated
icon: mdi:cloud-refresh-outline
```
