### ISSUE TITLE
Set Air Condition temperature for immediate start

### ISSUE THREAD

**Issue by wolfgangbures** [skodaconnect/homeassistant-myskoda#638]
There is currently no automation-"Action" to "start Air Condition now".
This would be a nice feature to prepare for departure in HomeAssistant and pre-heat the car

PS: Edit1 added info about Automation-Action that was missing

**Comment by suskozaver** [comment]
of course, there is? 

![Image](https://github.com/user-attachments/assets/fb7e4966-edea-4fce-abf0-6d5354d55d45)

`type: thermostat
entity: climate.skoda_octavia_ogrevanje_na_mestu
features:
  - type: climate-hvac-modes
show_current_as_primary: true
grid_options:
  columns: 12
  rows: 7
theme: Google Theme
`

**Comment by wolfgangbures** [comment]
Yes, i can do it manually, but there is no action in the automation (orry that was probably missing from inital issue - I am very new to HA)

![Image](https://github.com/user-attachments/assets/92070df5-6037-43bb-a44d-cd6b1ebd7956)

**Comment by suskozaver** [comment]
if you want to turn it on via automation use something like this bellow.

i have this on a button so the heating will start at 6:55 AM for a period of 20 minutes. 

```
sequence:
  - wait_for_trigger:
      - trigger: time
        at: "06:55:00"
    continue_on_timeout: false
  - device_id: cf5009e7975ed72488a3b700ba8d73c1
    domain: number
    entity_id: 0e82a58b9f7cf13d96a8552a659574f5
    type: set_value
    value: 20
  - device_id: cf5009e7975ed72488a3b700ba8d73c1
    domain: climate
    entity_id: 7f56825d2738aea0f3e423cb6690e109
    type: set_hvac_mode
    hvac_mode: heat
alias: Škoda Octavia - ogrevanje - 15 min - odhod ob 07:15
description: ""
```
