### ISSUE TITLE
Update documentation for disable polling

### ISSUE THREAD

**Issue by VedMod** [skodaconnect/homeassistant-myskoda#669]
In the readme it says, i can disable the polling. But how? In the config dialog i can set the value only between 1 and 1440.  
0 (zero) is not possible to submit!

Also the example of the action is wrong/outdated:
`target: `
is not valid / HA is missing the Data entry.
Also what is device_tracker.skoda_4ever ? I don't have this entity, i only have a similar entity with `device_tracker. "something like enyaq currentlocation"`

In the PR for the feature i found another example
https://github.com/skodaconnect/homeassistant-myskoda/issues/151#issuecomment-2449802919
but here is also the question what is sensor.mycar_mysensor ? One entity from the device? One custom created one?

**Comment by dvx76** [comment]
> In the readme it says, i can disable the polling. But how?

It's a standard HA feature - not specific to the integration. It's in the system options of the (any) configured integration, e.g. 

![Image](https://github.com/user-attachments/assets/047e634a-9706-4895-b036-2f54d5563e64)

**Comment by dvx76** [comment]
> the example of the action is wrong/outdated

Working example:

```yaml
action: homeassistant.update_entity
target:
  entity_id: device_tracker.skoda_enyaq_position
data:
  entity_id:
    - device_tracker.skoda_enyaq_position
```
