### ISSUE TITLE
Add charging history into HomeAssistant

### ISSUE THREAD

**Issue by Olkki** [skodaconnect/homeassistant-myskoda#733]
### Please confirm:

- [x] I have searched the existing open and closed issues this problem
- [x] I have updated the integration to the latest available version

### Home Assistant installation and version

HAOS 2025.3.4

### Car model

Enyaq coupe 85

### Feature Description

Myskoda app has charging history kwh data. Is this data possible to show in HA ?

**Comment by WebSpider** [comment]
This data has been added in version 8.1.0 of the app, which is about a week old now. It has not yet been added to the integration.

Thanks for opening this feature request, we will consider adding this!

**Comment by WebSpider** [comment]
Some inspiration from another integration that fetches historic data and inserts it as statistics:

https://github.com/home-assistant/core/pull/131166/files

**Comment by riesi77** [comment]
I would love to see that as well. And with that, there could probably also be a "charged total" sensor so I don't have to derive it from an integral over the charging power.

**Comment by WebSpider** [comment]
> I would love to see that as well. And with that, there could probably also be a "charged total" sensor so I don't have to derive it from an integral over the charging power.

Thanks for the suggestion, this looks to be a good application for the charging history. We're currently working on implementing this, there are a few things left to iron out.

**Comment by ybeid** [comment]
Could this be used for device based energy tracking in the energy dashboard?

The history doesn't include charge location but perhaps one could log location of charge events then match them to the energy charged listed in the history ?
This would allow tracking of energy used for home charging.

**Comment by WebSpider** [comment]
> Could this be used for device based energy tracking in the energy dashboard?

Maybe. 

> The history doesn't include charge location but perhaps one could log location of charge events then match them to the energy charged listed in the history ?

Possibly. 

> This would allow tracking of energy used for home charging.

Yeah, but for now let's focus in making this happen. We're in need of the knowledge to select begin/enddate of charging history, or how the app does that. Right now, we can see only a few charging sessions.

**Comment by WebSpider** [comment]
Small update: I've figured out how to set the start/enddate. This will make the first iteration available on v1.29 of the integration, which should be in a few days/weeks.

**Comment by riesi77** [comment]
Can you give us a short info on when you are planning to release 1.29?

**Comment by riesi77** [comment]
1.29.2 is released, but the feature is not contained, or did I miss something? Could you tell us when you plan for that (charging history in HA)? Thanks.

**Comment by riesi77** [comment]
Any heads up when this will come?

**Comment by dvx76** [comment]
I can try to take a look at this when I return from vacation.

This is not trivial information to represent in HA. Will need to take a look at how other car integrations do this.

> And with that, there could probably also be a "charged total" sensor so I don't have to derive it from an integral over the charging power.

That doesn't seem to be something the Skoda API is reporting (sample below). So probably won't be in the integration itself, but would be something users can accurately calculate if all charging sessions are available.

In the meantime, PRs or suggestions on how to model this in HA are welcome 😄 

Sample data, for future reference:

```
applicable_filter_options:
- filter_type: VEHICLE
  id: <VIN>
  label: <PLATE>
csv_file: IlNlc3Npb24gSUQiLCJTdGFydGVkIG9uIiwiRW5kZWQgb24iLCJDaGFyZ2luZyB0aW1lIChzKSIsIkFjdHVhbCBjaGFyZ2luZyB0aW1lIChzKSIsIlRvdGFsIGVuZXJneSAoa1doKSIsIkJhdHRlcnkgZW5lcmd5IChrV2gpIiwiIiJDb21mb3J0IiIgZW5lcmd5IChrV2gpIiwiU3RhcnQgU09DICglKSIsIkVuZCBTT0MgKCUpIiwiVG90YWwgcHJpY2UiLCJFbmVyZ3kgcHJpY2UiLCJCbG9ja2luZyBmZWVzIiwiVm91Y2hlciBhbW91bnQgdXNlZCIsIkxvY2F0aW9uIG5hbWUiLCJDaGFyZ2luZyBsb2NhdGlvbiINCiI5NzcwYmJmNC1jYjNkLTQyYWItYjlkNy0wNDQ5NTgwMzU4YmMiLCIyMDI2LTA3LTIwVDEyOjAyOjQ4WiIsIjIwMjYtMDctMjBUMTQ6Mzg6MzZaIiwiOTM0OCIsIjkzMzYiLCIxMS4wMCIsIiIsIiIsIjYyLjAwIiwiNzUuMDAiLCIiLCIiLCIiLCIiLCIiLCIiDQoiNTczMzFmMjMtZGU2Ni00ZWI3LWI2NjQtZWQ2OWJlNDRhMWJhIiwiMjAyNi0wNy0yMFQwOToxNDoyNFoiLCIyMDI2LTA3LTIwVDExOjAyOjMwWiIsIjY0ODYiLCI2NDc2IiwiNC4wMCIsIiIsIiIsIjYyLjAwIiwiNjUuMDAiLCIiLCIiLCIiLCIiLCIiLCIiDQo=
missing_elli_consent: false
month_sections:
- entries:
  - details:
      charging_end_time: '2026-07-20T14:38:36+00:00'
      charging_power_type: AC
      charging_start_time: '2026-07-20T12:02:48+00:00'
      formatted_active_charging_time: 2h 35min
      formatted_charging_end_time: 20/07/2026, 14:38
      formatted_charging_start_time: 20/07/2026, 12:02
      formatted_end_soc: 75%
      formatted_start_soc: 62%
      formatted_total_charging_time: 2h 35min
      formatted_total_energy: ~ 11 kWh
      is_active_session: false
      is_curve_available: true
      session_id: 9770bbf4-cb3d-42ab-b9d7-0449580358bc
    id: WvCexf-ttb2AlD9w_Ogx1C4CBLfVRPI8sX2FwgP5aTU
    primary_value: ~ 11 kWh
    secondary_value: 2h 35min
    title: Mon 20/07/2026, 12:02
  - details:
      charging_end_time: '2026-07-20T11:02:30+00:00'
      charging_power_type: AC
      charging_start_time: '2026-07-20T09:14:24+00:00'
      formatted_active_charging_time: 1h 47min
      formatted_charging_end_time: 20/07/2026, 11:02
      formatted_charging_start_time: 20/07/2026, 09:14
      formatted_end_soc: 65%
      formatted_start_soc: 62%
      formatted_total_charging_time: 1h 48min
      formatted_total_energy: ~ 4 kWh
      is_active_session: false
      is_curve_available: true
      session_id: 57331f23-de66-4eb7-b664-ed69be44a1ba
    id: aYoyG9g0OOpHep9DO5JwZJVyOnK7xkPYogI80mphEe0
    primary_value: ~ 4 kWh
    secondary_value: 1h 48min
    title: Mon 20/07/2026, 09:14
  title: July 2026
```
