### ISSUE TITLE
Dynamic polling interval depending on car state

### ISSUE THREAD

**Issue by roofburner** [skodaconnect/homeassistant-myskoda#802]
### Please confirm:

- [x] I have searched the existing open and closed issues this problem
- [x] I have updated the integration to the latest available version

### Home Assistant installation and version

2025.5.1

### Integration version

1.24.1

### Car model

Enyaq 85

### Feature Description

Is there any way, or is it and idea, to reconfigure the integrations polling interval via an input selection (I will need a service), in stead of the need to go via Setting->Devices->MySkoda->Configure?

I want to force the update interval to 1m when driving and change it back tot 30m when idle.
It would that be useless?

**Comment by WebSpider** [comment]
It's a better idea to use the `homeassistant.update_entity` service in an automation to pull updates while you are driving.

Reason is we need to restart the integration when we change the polling interval

**Comment by roofburner** [comment]
OK. I implemented this. My I configured my integration at 1440, thus one forced refresh every day, if no earlier refresh occures.

configuration.yaml:
```
input_select:
  skoda_refresh_rate:
    name: Skoda refresh rate
    options:
      - 1
      - 5
      - 10
      - 30
      - 60
      - 720
    initial: "720"
```

Start at refresh rate of 12h (720 minutes). If driving, I can change to 1 minute (don't know if Skoda cloud gets updated that fast?).

automation.yaml:
```
- id: refresh Skoda
  alias: "Skoda refresh (dynamic interval)"
  mode: restart
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_select.skoda_refresh_rate
  action:
    - repeat:
        while: []
        sequence:
          - service: homeassistant.update_entity
            target:
              entity_id: device_tracker.skoda_enyaq_position
          - delay:
              minutes: >
                {{ states('input_select.skoda_refresh_rate') | int }}
```

Maybe next step is to change the refresh rate using an automation e.g. when the vehicle is in motion, charging, ... and retore the refresh rate to 12h when not in motion, not charging, ...

Any improvements/suggestions?
