### ISSUE TITLE
Calculate absolute time for charging complete, not only relative.

### ISSUE THREAD

**Issue by bardahlm** [skodaconnect/homeassistant-myskoda#847]
### Please confirm:

- [x] I have searched the existing open and closed issues this problem
- [x] I have updated the integration to the latest available version

### Home Assistant installation and version

2025.6.3, container

### Integration version

1.28.3

### Car model

Enyaq 80

### Feature Description

The Remaining Charging Time sensor show an estimation on how long it would take to charge the car to the specified battery level. If its been a long time since updates, one might see values as 2 hours to charge for 2 hours ago, meaning that the car might already be finished charging.
Therefore it could be useful to also calculate absolute time for when charging should be complete.

### MySkoda App Behavior

The app shows remaining time and the corresponding clock time. Note that the app seems to calculate the time when viewed, so it will be off if data is old.

**Comment by dvx76** [comment]
Thanks for your submission. The Skoda API doesn't return this directly but it should be trivial to calculate into a separate sensor.

FWIW in cards which take javascript (e.g. button-card) you can calculate this with something like

```
            var tzoffset = (new Date()).getTimezoneOffset() * 60000;
            var timeRemaining = (Number(states['sensor.skoda_enyaq_remaining_charging_time'].state) || 0) * 60 * 1000;
            const d = new Date(new Date().getTime() - tzoffset + timeRemaining).toISOString().slice(11, 16);
```

Or with Jinja

```
{{ now() + timedelta(minutes=int(states.sensor.skoda_enyaq_remaining_charging_time.state)) }}
```

**Comment by bardahlm** [comment]
I created a helper of type input_datetime, and the following automation:

```yaml
alias: Charging complete
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.skoda_enyaq_remaining_charging_time
conditions: []
actions:
  - action: input_datetime.set_datetime
    target:
      entity_id: input_datetime.charging_complete
    data:
      datetime: >-
        {{ now() +
        timedelta(hours=float(states.sensor.skoda_enyaq_remaining_charging_time.state))
        }}
mode: single
```

I've set skoda_enyaq_remaining_charging_time to hours, so had to modify the template a bit. I guess there is a more portable way to get the remaining charge time.
